{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "helm.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: twtr-dev.com # In /etc/hosts, this maps to my cluster's ip
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-gateway
            servicePort: http
    - host: traefik.dashboard.com
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-traefik-dashboard
            servicePort: 80
{{- end }}
